### POST image
POST http://localhost:3000/api/images
Content-Type: application/json

{
    "name": "Nihari Upgrade",
    "image_link": "https://i.ndtvimg.com/i/2017-06/nihari_650x400_81498470650.jpg"
}

### GET all 
GET http://localhost:3000/api/images


### GET fist 
GET http://localhost:3000/api/images/1


### GET too low 
GET http://localhost:3000/api/images/-1


### GET too high
GET http://localhost:3000/api/images/30


### PUT 
PUT http://localhost:3000/api/images/17
Content-Type: application/json

{
    "name": "Nihari Updated to Delete",
    "image_link": "https://i.ndtvimg.com/i/2017-06/nihari_650x400_81498470650.jpg"
}


### DELETE
DELETE http://localhost:3000/api/images/17